{{- if .Values.namespaces }}
{{- range $ns := .Values.namespaces }}
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: {{ $.Values.name }}
  labels:
    app: {{ $.Values.name }}
  {{- if not $.Values.ignoreHelmHooks }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  {{- end }}
  namespace: {{ $ns }}
spec:
  applicationInstanceLabelKey: gxfs/{{ $ns }}
  {{- if $.Values.argocd_cr }}
  {{- $.Values.argocd_cr | toYaml | trim | nindent 2 }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  {{- if not $.Values.ignoreHelmHooks }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  {{- end }}
  namespace: {{ $ns }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
status: {}
{{- end }}
{{- end }}
{{- if .Values.operator.clusterArgoCD }}
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  {{- if not .Values.ignoreHelmHooks }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if $.Values.argocd_cr }}
  {{- $.Values.argocd_cr | toYaml | trim | nindent 2 }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  {{- if not $.Values.ignoreHelmHooks }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
status: {}
{{- end }}