{{- if .Values.operator }}
{{- if .Values.operator.operatorgroup }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
  - {{ .Release.Namespace }}
{{- end }}
{{- end }}