{{- if .Values.operator }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  channel: {{ .Values.operator.channel }}
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  name: {{ .Values.operator.name }}
  source: {{ .Values.operator.sourceName | default "operatorhubio-catalog" | quote }}
  sourceNamespace: {{ .Values.operator.sourceNamespace | default "olm" | quote }}
{{- if .Values.operator.version }}
  startingCSV: {{ .Values.operator.version | quote }}
{{- end }}
  config:
    env:
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
      value: "true"
{{- if .Values.operator.clusterArgoCD }}
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: "*"
{{- else if and (.Values.namespaces) (.Values.teamInstancesAreClusterScoped) }}
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: {{ join "," .Values.namespaces | quote }}
{{- end }}
{{- end }}
