apiVersion: v2
name: tsa-policy-sync
description: A Helm chart that creates a tsa policy sync.
version: 1.0.32

dependencies:
  - name: library
    version: 1.0.0
    repository: "https://gitlab.com/api/v4/projects/40471958/packages/helm/stable/"
