{{- if .Values.redis }}
{{- range $redis := .Values.redis }}
{{- if .enabled }}
{{- if and .follower .externalService }}
{{- if and (gt (int .follower.replicas) 0) (eq .externalService.enabled true) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-follower-external-service
{{- if .externalService.annotations }}
  annotations:
{{ toYaml .externalService.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/component: middleware
spec:
  type: {{ .externalService.serviceType }}
  selector:
    app: {{ .name }}-follower
    redis_setup_type: follower
    role: follower
  ports:
    - protocol: TCP
      port: {{ .externalService.port }}
      targetPort: 6379
      name: client
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}