{{- if .Values.redis }}
{{- if .Values.redisSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.redisSecret.secretName}} 
  namespace: {{ .Release.Namespace}}
labels:
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  password: {{ .Values.mongodb.password | b64enc }} #change to random string
type: Opaque
{{- end }}
{{- end }}
