{{- if .Values.mongodb.password }}
{{- $mongodbPassword := printf "%s" .Values.fullnameOverride }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $mongodbPassword }}
  namespace: {{ $.Release.Namespace }}
data:
  password: {{ .Values.mongodb.password | b64enc }} #change to random string
type: Opaque
{{- end }}
