{{- if hasKey .Values "externalKeycloak" }}
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: ExternalKeycloak
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  url: {{ printf "https://%s-service:8443" .Values.name }} # set to the Service created by the new Keycloak Operator
  contextRoot: /
{{- end }}
